name: Build for Android

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-android:
    name: Release Android
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.x"
          cache: true

      - name: Write signing config
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ -n "${{ secrets.SIGN_KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.SIGN_KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.jks
            echo "storeFile=key.jks" >> android/key.properties
            echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
            echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
            echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          fi

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Rename artifacts
        run: |
          for file in build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(echo "$file" | sed -E 's|.*app-(.*)-release\.apk|\1|')
            mv "$file" "adaptive_glass_${abi}.apk"
          done
        shell: bash

      - name: Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          files: |
            adaptive_glass_*.apk

      - name: Upload arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: Android-arm64-v8a
          path: adaptive_glass_arm64-v8a.apk

      - name: Upload armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: Android-armeabi-v7a
          path: adaptive_glass_armeabi-v7a.apk

      - name: Upload x86_64
        uses: actions/upload-artifact@v4
        with:
          name: Android-x86_64
          path: adaptive_glass_x86_64.apk
