name: Build for Web

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-web:
    name: Release Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.x"
          cache: true

      - name: Build Web
        run: flutter build web --release

      - name: Upload web release
        uses: actions/upload-artifact@v4
        with:
          name: Web-release
          path: build/web/
